[project]
org-name = "i_dont_remember"
version = "0.2.0"
authors = ["i-dont-remember"]
keywords = ["time", "datetime", "date", "moment", "timestamp"]
repository = "https://github.com/i-dont-remember/thyme"